# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build do
    set_info_plist_value(path: "./LS1DrinksAccounting/Info.plist", key: "APP_VERSION", value: sh("git describe --tags --dirty --always | sed 's/^v\(.*\)/\1/' | tr -d 'v\n'"))
    build_app(
      configuration: "Release",
      export_method: "development"
    )
  end
end

