name: ci

on:
  push:
    tags:
      - '*'

jobs:
  build-dashboard:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:dashboard"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ls1-drinks-accounting-dashboard:latest, ${{ secrets.DOCKERHUB_USERNAME }}/ls1-drinks-accounting-dashboard:${{ github.ref_name }}
  build-backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ls1-drinks-accounting:latest, ${{ secrets.DOCKERHUB_USERNAME }}/ls1-drinks-accounting:${{ github.ref_name }}
